"""adding evidence_urls column in bribe table and removing evidence file, name and its content type columns

Revision ID: a8db39131e93
Revises: ad02405ff407
Create Date: 2025-04-02 14:02:13.554981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a8db39131e93'
down_revision: Union[str, None] = 'ad02405ff407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bribe', sa.Column('evidence_urls', sa.JSON(), nullable=True))
    op.drop_column('bribe', 'evidence')
    op.drop_column('bribe', 'evidence_filename')
    op.drop_column('bribe', 'evidence_content_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bribe', sa.Column('evidence_content_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bribe', sa.Column('evidence_filename', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('bribe', sa.Column('evidence', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('bribe', 'evidence_urls')
    # ### end Alembic commands ###
