"""Add evidence filename and content type to Bribe table

Revision ID: ad02405ff407
Revises: 
Create Date: 2025-04-01 13:59:10.613048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ad02405ff407'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bribe', sa.Column('evidence_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('bribe', sa.Column('evidence_content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bribe', 'evidence_content_type')
    op.drop_column('bribe', 'evidence_filename')
    # ### end Alembic commands ###
